name: py38_pyhdx_dev
channels:
  - defaults
  - pyviz
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - hdxrate[version='>=0.2.0']
  - numpy
  - matplotlib==3.4.3
  - pandas
  - scikit-image
  - scipy
  - symfit[version='>=0.5.5']
  - pytorch
  - tqdm
  - typer
  - dask
  - distributed
  - packaging
  - param
  - panel[version='>=0.12.6']
  - bokeh
  - holoviews
  - colorcet[version='>=3.0.0']
  - hvplot
  - proplot==0.9.3
  - pyyaml
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - furo
  - nbsphinx

