config:
  title: PyHDX app

main_controller:
  type: peptide

sources:
  main:
    type: table

opts:
  base:
    type: generic
    responsive: True
    framewise: True
    show_grid: True
  d_uptake:
    type: generic
    logx: True
    xlabel: Time (s)
    ylabel: D uptake
    tools:
      - hover

tools:
  hover:
    type: hover
    tooltips:
      - ["Time (s)", '$x']
      - ['D-uptake', '$y']

views:
  peptide_uptake:
    type: curve
    source: main
    opts:
      - base
      - d_uptake

    x: time
    y: sum

  aa_uptake:
    type: curve
    source: main
    opts:
      - base
      - d_uptake
    x: time
    y: aa_0
    y_objects: !regexp aa_\d


controllers:
  - peptide
