config:
  title: PyHDX app

main_controller:
  type: pyhdx
  #kwargs: ...

sources:
  main:
    type: pyhdx

filters:
  peptide_src:
    type: table_source
    source: main
    table: peptides
  rfu_src:
    type: table_source
    source: main
    table: rfu_residues
  rates_src:
    type: table_source
    source: main
    table: rates
  dG_src:
    type: table_source
    source: main
    table: dG_fits
  ddG_src:
    type: table_source
    source: main
    table: ddG_comparison
  protein_src:  # table source which exposued widget which can be used to select which table to use for colors
    type: table_source
    source: main
    table_options:
      - rfu_residues
      - dG_fits
      - ddG_comparison

opts:
  base:
    type: generic
    responsive: True
    framewise: True
    show_grid: True
  errorbars:
    type: generic
    line_alpha: 0.5
    line_color: '#8c8c8c'
    apply_ranges: False
    hooks:
      - handle: glyph
        attr: upper_head.line_color
        value: '#8c8c8c'
      - handle: glyph
        attr: lower_head.line_color
        value: '#8c8c8c'
  scatter:
    type: generic
    size: 8
  rfu:
    type: cmap
    field: rfu
  dG:  # perhaps they need better names?
    type: cmap
    field: deltaG
    sclf: 1.0e-3
  ddG:
    type: cmap
    field: ddG
    sclf: 1.0e-3
  info_log:
    type: generic
    title: Log Window
  debug_log:
    type: generic
    title: Debug Log

tools:
  coverage_hover:
    type: hover
    tooltips:
      - ['id', '$index']
      - ['RFU', '@rfu']
      - ['D (corrected)', '@uptake_corrected']
      - ['sequence', '@sequence']
  rfu_hover:
    type: hover
    tooltips:
      - ['Residue', '@r_number']
      - ['RFU', '@rfu']
    # mode: vline
    #only show closest hit:
    #https://stackoverflow.com/questions/36434562/displaying-only-one-tooltip-when-using-the-hovertool-tool
    #https://github.com/bokeh/bokeh/issues/9087
  rates_hover:
    type: hover
    tooltips:
      - ['Residue', '@r_number']
      - ['Rate', '@rate s⁻¹']
    #mode: vline
  dG_hover:
    type: hover
    tooltips:
      - [ 'Residue', '@r_number' ]
      - [ 'ΔG', '@deltaG kJ/mol' ]
    #mode: vline
  ddG_hover:
    type: hover
    tooltips:
      - [ 'Residue', '@r_number' ]
      - [ 'ΔΔG', '@ddG kJ/mol' ]

views:
  logging_info:
    type: logging
    source: None
    logger: pyhdx
    level: 20
    opts:
      - info_log
  logging_debug:
    type: logging
    source: None
    logger: pyhdx
    level: 10
    opts:
      - debug_log

modules:
  coverage_view:
    filters:
      coverage_select:
        type: cross_section
        source: peptide_src
        n_levels: 2
      coverage_rectangles:
        type: rectangle_layout
        source: coverage_select
        left: start
        right: end
        passthrough:
          - rfu
          - uptake_corrected
          - sequence
    opts:
      coverage:
        type: generic
        color: rfu
        colorbar: True
        xlabel: Residue Number
        ylabel : ''
        yticks: 0
        title: Peptide coverage
        tools:
          - coverage_hover
    views:
      coverage:
        type: rectangles
        source: coverage_rectangles
        opts:
          - base
          - coverage
          - rfu
        vdims:
          - rfu
          - uptake_corrected
          - sequence

  rfu:
    filters:
      rfu_select:
        type: cross_section
        source: rfu_src
        n_levels: 0
      rfu_droplevel:
        type: droplevel
        source: rfu_select
        level: 0
        axis: 1   # todo expand columns to include qty (perhaps this already done)
      rfu_rename:
        type: rename
        source: rfu_droplevel
        columns:
          - rfu
    opts:
      rfu_scatter:
        type: generic
        xlabel: Residue Number
        ylabel: RFU
        title: RFU Scatter
        color: rfu
        colorbar: True
        tools:
          - rfu_hover
    views:
      rfu_scatter:
        type: scatter
        source: rfu_rename
        x: r_number
        y: rfu
        opts:
          - base
          - scatter
          - rfu_scatter
          - rfu  # rename rfu_cmap
        #x: r_number

  rates:
    filters:
      rates_select:
        type: cross_section
        source: rates_src
        n_levels: 2
    opts:
      rates:
        type: generic
        xlabel: Residue Number
        ylabel: Rate (s⁻¹)  # todo superscript
        title: Approximate H/D rates
        logy: True
        tools:
          - rates_hover
    views:
      rates:
        type: scatter
        source: rates_select
        opts:
          - base
          - scatter
          - rates
        x: r_number
        y: rate

  dG:
    filters:
      dG_fit_select:
        type: cross_section
        source: dG_src
        n_levels: 2
      dG_rescale:
        type: rescale
        source: dG_fit_select
        scale_factor: 1.0e-3
        columns:
        - deltaG
        - covariance
    opts:
      dG_axes:
        type: generic
        xlabel: Residue Number
        ylabel: ΔG (kJ/mol)
        title: ΔG Scatterplot
        invert_yaxis: True
        color: deltaG
        colorbar: True
        tools:
          - dG_hover
    views:
      gibbs: # todo rename dG??
        type: scatter
        source: dG_rescale
        opts:
          - base
          - scatter
          - dG_axes
          - dG
        x: r_number
        y: deltaG
      gibbs_errors:
        type: errorbars
        source: dG_rescale
        opts:
          - base
          - errorbars
        pos: r_number
        value: deltaG
        err: covariance
      gibbs_overlay:
        type: overlay
        views:
          - gibbs
          - gibbs_errors

  ddG_view:
    filters:
      ddG_comparison_select:
        type: cross_section
        source: ddG_src
        n_levels: 2
      ddG_rescale:
        type: rescale
        source: ddG_comparison_select
        scale_factor: 1.0e-3   # TODO sclf vs scale_factor
        columns:
        - ddG  # todo expand columns to include qty
        - covariance
    opts:
      ddG_axes:
        type: generic
        xlabel: Residue Number
        ylabel: ΔΔG (kJ/mol)
        title: ΔΔG Scatterplot
        invert_yaxis: True # todo find out of symmetric around zero constraint is possible
        color: ddG
        colorbar: True
        tools:
          - ddG_hover
    views:
      ddG:
        type: scatter
        source: ddG_rescale
        opts:
          - base
          - scatter
          - ddG_axes
          - ddG  # = cmap, raname
        x: r_number
        y: ddG
      ddG_errors:
        type: errorbars
        source: ddG_rescale
        opts:
          - base
          - errorbars
        pos: r_number
        value: ddG
        err: covariance
      ddG_overlay:
        type: overlay
        views:
          - ddG
          - ddG_errors

  # todo manual field for temporari things which cannot be yaml'd
  protein_view:
    filters:
      protein_select:
        type: cross_section
        source: protein_src
      protein_cmap:
        type: apply_cmap_opt
        source: protein_select
        opts:
          - rfu  #cmap opts, -> renmame
          - dG
          - ddG
    views:
      protein:  #NGL?
        type: ngl
        source: protein_cmap
        dependencies:
          opts:
            - rfu
            - dG
            - ddG
  ddG_control:
    filters:
      ddG_fit_select:
        type: cross_section
        source: dG_src
        n_levels: 1

controllers:
  #- peptide_file_input  # todo by name ?
  #- initial_guess
  - dev
  - peptide_file_input
  - initial_guess
  - fit
  - comparison
  - color_transform
  - protein  #rename: NGL?
  - graph
  - file_export
  - figure_export
  - session_manager
